# Generated by Django 5.2.5 on 2025-08-24 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6da87c3-4ab1-4b1e-8992-1d8d907e5b81'), primary_key=True, serialize=False, unique=True),
        ),
    ]
